"""CVXPY-style modelling of (sparse) sum-of-squares constraints.

The public API mirrors CVXPY's LMI interface: ``P >> 0`` on a
:class:`PolyMatrix` (or a scalar :class:`~pysparsepmi.polynomial.Polynomial`)
creates a constraint object, and :class:`Problem` couples an ordinary CVXPY
objective with a list of such constraints::

    import cvxpy as cp
    import pysparsepmi as psp

    x, = psp.polyvar(1)
    t = cp.Variable()
    F = psp.PolyMatrix([[1 + x**2, x], [x, 1]])
    prob = psp.Problem(cp.Maximize(t), [F - psp.eye(2, nvars=1) * t >> 0])
    prob.solve(solver="SCS")

``P >> 0`` is interpreted as "P admits a sum-of-squares certificate":

* for a scalar polynomial, a Gram (SOS) decomposition whose monomial basis is
  split across the maximal cliques of the correlative sparsity pattern of the
  variables — the behaviour of YALMIP's ``sos.csp`` option;
* for a polynomial matrix, the chordal decomposition
  ``P = sum_k E_k' S_k(x) E_k`` of Zheng & Fantuzzi (2020), with one SOS
  matrix ``S_k`` per maximal clique of the (chordally extended) sparsity
  pattern of ``P``.

Both reduce to the classical dense SOS constraint when ``sparse=False``.
"""
from __future__ import annotations

from collections import defaultdict
from itertools import product

import numpy as np
import cvxpy as cp

from .polynomial import (
    Polynomial,
    _is_number,
    _is_scalar_expression,
    as_polynomial,
    ball_multiplier,
    poly_matrix,
)
from .chordal import chordal_cliques, correlative_sparsity
from .basis import gram_candidates, reduce_bases
from .termsparsity import ts_matrix_blocks

__all__ = [
    "PolyMatrix",
    "eye",
    "SOS",
    "SOSMatrix",
    "Problem",
    "SOSInfeasibleError",
    "sos_poly_variable",
    "sos_matrix_variable",
]


class SOSInfeasibleError(ValueError):
    """Raised when an SOS constraint is structurally infeasible.

    This happens when a monomial with a nonzero numeric coefficient cannot be
    generated by any product of Gram-basis monomials (e.g. an odd maximal
    degree, or a term excluded by the sparsity pattern).
    """


# ======================================================================
# Polynomial matrices
# ======================================================================
class PolyMatrix:
    """A square symmetric matrix of polynomials, supporting ``P >> 0``.

    Entries may be polynomials, numbers, or scalar CVXPY expressions.
    Arithmetic (+, -, scalar *, @) is supported, mirroring how CVXPY
    expressions combine before being turned into constraints with ``>>``.
    """

    __array_ufunc__ = None
    __array_priority__ = 2000.0

    def __init__(self, data, nvars=None):
        if isinstance(data, PolyMatrix):
            self.arr = data.arr.copy()
        else:
            self.arr = poly_matrix(data, nvars)
        self.nvars = self.arr[0, 0].nvars

    @property
    def shape(self):
        return self.arr.shape

    def __getitem__(self, idx):
        out = self.arr[idx]
        if isinstance(out, np.ndarray):
            return PolyMatrix(out)
        return out

    # -- arithmetic ----------------------------------------------------
    def _other_arr(self, other):
        if isinstance(other, PolyMatrix):
            return other.arr
        if isinstance(other, (list, tuple, np.ndarray)):
            return poly_matrix(other, self.nvars)
        return None

    def __add__(self, other):
        arr = self._other_arr(other)
        if arr is None:
            return NotImplemented
        if arr.shape != self.arr.shape:
            raise ValueError("shape mismatch in PolyMatrix addition")
        return PolyMatrix(self.arr + arr)

    __radd__ = __add__

    def __sub__(self, other):
        arr = self._other_arr(other)
        if arr is None:
            return NotImplemented
        return PolyMatrix(self.arr - arr)

    def __rsub__(self, other):
        arr = self._other_arr(other)
        if arr is None:
            return NotImplemented
        return PolyMatrix(arr - self.arr)

    def __mul__(self, other):
        # scalar multiplication only (number, Polynomial, or CVXPY scalar)
        if isinstance(other, (Polynomial,)) or _is_number(other) or _is_scalar_expression(other):
            out = np.empty(self.arr.shape, dtype=object)
            for idx in np.ndindex(self.arr.shape):
                out[idx] = self.arr[idx] * other
            return PolyMatrix(out)
        return NotImplemented

    __rmul__ = __mul__

    def __neg__(self):
        return self * (-1.0)

    def __matmul__(self, other):
        arr = self._other_arr(other)
        if arr is None:
            return NotImplemented
        m = self.arr.shape[0]
        out = np.empty((m, arr.shape[1]), dtype=object)
        for i in range(m):
            for j in range(arr.shape[1]):
                s = Polynomial.zero(self.nvars)
                for k in range(arr.shape[0]):
                    s = s + self.arr[i, k] * arr[k, j]
                out[i, j] = s
        return PolyMatrix(out)

    # -- LMI-style constraint creation ----------------------------------
    def __rshift__(self, other):
        """``P >> other``: P - other admits a sparse SOS-matrix certificate."""
        return SOSMatrix(self._shift_diff(other, right=True))

    def __lshift__(self, other):
        """``P << other``: other - P admits a sparse SOS-matrix certificate."""
        return SOSMatrix(self._shift_diff(other, right=False))

    def _shift_diff(self, other, right):
        if _is_number(other) and other == 0:
            diff = self
        else:
            arr = self._other_arr(other)
            if arr is None:
                raise TypeError("cannot compare PolyMatrix with %r" % (other,))
            diff = PolyMatrix(self.arr - arr)
        return diff if right else -diff

    def __repr__(self):
        return "PolyMatrix(%dx%d, nvars=%d)" % (
            self.shape[0],
            self.shape[1],
            self.nvars,
        )


def eye(m, nvars):
    """The m-by-m identity as a :class:`PolyMatrix` in ``nvars`` variables."""
    arr = np.empty((m, m), dtype=object)
    for i in range(m):
        for j in range(m):
            arr[i, j] = Polynomial.constant(nvars, 1.0 if i == j else 0.0)
    return PolyMatrix(arr)


# ======================================================================
# Constraint objects
# ======================================================================
class SOS:
    """Scalar SOS constraint: ``p`` is a sum of squares.

    With ``sparse=True`` (default) the Gram basis is split over the maximal
    cliques of the correlative sparsity pattern of the variables of ``p`` —
    the behaviour of YALMIP's ``sos.csp`` option. ``cliques`` overrides the
    automatic clique detection (a list of iterables of variable indices).

    ``ts`` additionally imposes term sparsity (TSSOS; Miller, Wang & Guo,
    arXiv:2411.15479) on each Gram matrix: ``"block"`` uses the block
    closure of the term sparsity pattern graph, ``"MD"`` a greedy
    minimum-degree chordal closure, and each clique of the stabilized graph
    becomes one small PSD block. ``ts_order`` is the sparse order ``s``
    (number of support-extension steps; ``None`` iterates to stabilization,
    matching repeated ``tssos(data, TS=...)`` calls).

    After the enclosing :class:`Problem` is compiled, the attributes
    ``cliques``, ``bases``, ``grams``, ``blocks`` and ``block_sizes``
    describe the decomposition.
    """

    def __init__(self, poly, sparse=True, cliques=None, ts=None, ts_order=None):
        if isinstance(poly, PolyMatrix):
            raise TypeError("use SOSMatrix (or P >> 0) for polynomial matrices")
        self.poly = poly
        self.sparse = bool(sparse)
        self.cliques = None if cliques is None else [sorted(c) for c in cliques]
        self.ts = ts
        self.ts_order = ts_order
        self.bases = None
        self.grams = None
        self.blocks = None

    @property
    def block_sizes(self):
        if self.grams is None:
            return None
        return [0 if Q is None else Q.shape[0] for Q in self.grams]

    def compile(self):
        return _compile_sos(self)


class SOSMatrix:
    """Matrix SOS constraint: ``P(x)`` admits an SOS-matrix certificate.

    With ``sparse=True`` (default) the certificate is the chordal
    decomposition ``(x'x)^nu * P = sum_k E_k' S_k(x) E_k`` of Zheng &
    Fantuzzi (2020), with one SOS matrix ``S_k`` per maximal clique of the
    chordally extended sparsity pattern of ``P``. With ``sparse=False`` a
    single dense SOS matrix is used. ``nu=0`` by default; increasing ``nu``
    weakens the constraint towards positive semidefiniteness of ``P`` away
    from the origin (Theorem 3.4 in the paper).

    ``ts`` additionally imposes term sparsity (TSSOS-style; Miller, Wang &
    Guo, arXiv:2411.15479, Section 3.2) inside each clique's Gram matrix:
    the term sparsity pattern graph on nodes ``(row, basis monomial)`` is
    grown by support extension plus either the block closure (``"block"``)
    or a minimum-degree chordal closure (``"MD"``), and each of its cliques
    becomes one small PSD block. ``ts_order`` is the sparse order ``s``
    (``None`` iterates to stabilization).
    """

    def __init__(self, P, sparse=True, nu=0, cliques=None, nvars=None, ts=None, ts_order=None):
        if isinstance(P, Polynomial):
            raise TypeError("use SOS (or p >> 0) for scalar polynomials")
        if not isinstance(P, PolyMatrix):
            P = PolyMatrix(P, nvars)
        self.P = P
        self.sparse = bool(sparse)
        self.nu = int(nu)
        self.cliques = None if cliques is None else [sorted(c) for c in cliques]
        self.ts = ts
        self.ts_order = ts_order
        self.bases = None
        self.grams = None
        self.blocks = None

    @property
    def block_sizes(self):
        if self.grams is None:
            return None
        return [0 if Q is None else Q.shape[0] for Q in self.grams]

    def compile(self):
        return _compile_sos_matrix(self)


# ======================================================================
# Gram-parameterized SOS objects (used to build multipliers/localizers)
# ======================================================================
def sos_poly_variable(nvars, basis):
    """An SOS polynomial "variable" ``s(x) = z(x)' Q z(x)`` with Q PSD.

    Returns ``(s, Q)`` where ``s`` is a Polynomial whose coefficients are
    affine in the entries of the PSD CVXPY variable ``Q`` (so ``s`` is SOS by
    construction and needs no extra constraint).
    """
    S, Q = sos_matrix_variable(nvars, 1, basis)
    return S[0, 0], Q


def sos_matrix_variable(nvars, size, basis):
    """An SOS-matrix "variable" of the given size over an x-monomial basis.

    Returns ``(S, Q)``: ``S`` is a ``size x size`` object array of Polynomials
    with ``S(x) = (z(x) kron I)' Q (z(x) kron I)`` for the PSD CVXPY variable
    ``Q``; it is an SOS matrix by construction.
    """
    basis = [tuple(b) for b in basis]
    nB = len(basis)
    if nB == 0:
        raise ValueError("empty basis")
    N = size * nB
    Q = cp.Variable((N, N), PSD=True)
    terms = [[defaultdict(list) for _ in range(size)] for _ in range(size)]
    for a, b in product(range(nB), repeat=2):
        gamma = tuple(x + y for x, y in zip(basis[a], basis[b]))
        for i in range(size):
            for j in range(i, size):
                terms[i][j][gamma].append(Q[a * size + i, b * size + j])
    S = np.empty((size, size), dtype=object)
    for i in range(size):
        for j in range(i, size):
            S[i, j] = Polynomial(
                nvars, {g: sum(lst) for g, lst in terms[i][j].items()}
            )
            S[j, i] = S[i, j]
    return S, Q


# ======================================================================
# Compilation to CVXPY constraints
# ======================================================================
def _match_coefficients(lhs, rhs_poly_terms, context):
    """Equate Gram-expansion coefficients with polynomial coefficients.

    ``lhs`` maps exponent tuples to lists of CVXPY scalar expressions;
    ``rhs_poly_terms`` maps exponent tuples to numeric or CVXPY coefficients.
    """
    constraints = []
    for gamma in set(lhs) | set(rhs_poly_terms):
        exprs = lhs.get(gamma)
        rhs = rhs_poly_terms.get(gamma, 0.0)
        if exprs:
            constraints.append(sum(exprs) == rhs)
        elif _is_number(rhs):
            if rhs != 0:
                raise SOSInfeasibleError(
                    "%s: monomial %r (coefficient %r) cannot be generated by "
                    "the Gram basis; the constraint is infeasible" % (context, gamma, rhs)
                )
        else:
            constraints.append(rhs == 0)
    return constraints


def _compile_sos(con):
    p = con.poly
    if not isinstance(p, Polynomial):
        raise TypeError("SOS expects a Polynomial")
    supp = list(p.terms)
    if not supp:
        con.cliques, con.bases, con.grams = [], [], []
        return []

    nvars = p.nvars
    if con.cliques is None:
        if con.sparse:
            _, con.cliques = correlative_sparsity(supp, nvars)
        else:
            con.cliques = [list(range(nvars))]

    bases = [gram_candidates(supp, nvars, vars=c) for c in con.cliques]
    con.bases = reduce_bases(bases, supp)

    lhs = defaultdict(list)
    con.grams = []
    con.blocks = []
    numeric_supp = set(supp)
    for B in con.bases:
        if not B:
            con.grams.append(None)
            continue
        if con.ts:
            blocks, _ = ts_matrix_blocks(
                {(0, 0): numeric_supp}, [B], method=con.ts, max_steps=con.ts_order
            )
            block_bases = [[alpha for _, alpha in blk] for blk in blocks]
        else:
            block_bases = [B]
        for BB in block_bases:
            con.blocks.append(BB)
            Q = cp.Variable((len(BB), len(BB)), PSD=True)
            con.grams.append(Q)
            for a in range(len(BB)):
                for b in range(a, len(BB)):
                    gamma = tuple(x + y for x, y in zip(BB[a], BB[b]))
                    lhs[gamma].append(Q[a, b] if a == b else 2 * Q[a, b])
    return _match_coefficients(lhs, p.terms, "SOS")


def _compile_sos_matrix(con):
    P = con.P.arr
    m = P.shape[0]
    nvars = con.P.nvars

    if con.nu:
        w = ball_multiplier(nvars, con.nu)
        P = np.array(
            [[P[i, j] * w for j in range(m)] for i in range(m)], dtype=object
        )

    # symmetry check on numeric entries
    for i in range(m):
        for j in range(i + 1, m):
            if P[i, j].is_numeric() and P[j, i].is_numeric():
                if not P[i, j].equals(P[j, i]):
                    raise ValueError(
                        "PolyMatrix is not symmetric at entry (%d, %d)" % (i, j)
                    )

    if m == 1 and con.cliques is None:
        # scalar case: fall back to correlative (variable) sparsity
        inner = SOS(P[0, 0], sparse=con.sparse, ts=con.ts, ts_order=con.ts_order)
        out = inner.compile()
        con.cliques = [[0]]
        con.bases, con.grams, con.blocks = inner.bases, inner.grams, inner.blocks
        return out

    nonzero = [(i, j) for i in range(m) for j in range(m) if not P[i, j].is_zero()]
    if con.cliques is None:
        if con.sparse:
            pattern = np.zeros((m, m), dtype=int)
            for i, j in nonzero:
                pattern[i, j] = 1
            np.fill_diagonal(pattern, 1)
            con.cliques = chordal_cliques(pattern)
        else:
            con.cliques = [list(range(m))]

    covered = set()
    for C in con.cliques:
        covered.update(product(C, C))
    for i, j in nonzero:
        if (i, j) not in covered:
            raise ValueError(
                "cliques do not cover the nonzero entry (%d, %d) of the matrix"
                % (i, j)
            )

    # union of diagonal supports (used for degree bounds and basis reduction:
    # the extremal parts of the diagonal of an SOS matrix cannot cancel)
    diag_supp_all = set()
    for i in range(m):
        diag_supp_all.update(P[i, i].terms)

    bases = []
    for C in con.cliques:
        diag_supp = set()
        for i in C:
            diag_supp.update(P[i, i].terms)
        bases.append(gram_candidates(diag_supp, nvars))
    con.bases = reduce_bases(bases, diag_supp_all)

    lhs = {}  # (i, j) i<=j -> {gamma: [exprs]}
    con.grams = []
    con.blocks = []
    for C, B in zip(con.cliques, con.bases):
        mk, nB = len(C), len(B)
        if nB == 0:
            con.grams.append(None)
            continue
        if con.ts:
            supports = {}
            for ii in range(mk):
                for jj in range(ii, mk):
                    supports[(ii, jj)] = set(P[C[ii], C[jj]].terms)
            blocks, _ = ts_matrix_blocks(
                supports, [B] * mk, method=con.ts, max_steps=con.ts_order
            )
            for blk in blocks:
                con.blocks.append([(C[ii], alpha) for ii, alpha in blk])
                nblk = len(blk)
                Q = cp.Variable((nblk, nblk), PSD=True)
                con.grams.append(Q)
                # ordered node pairs with row(a) <= row(b) fill the upper
                # triangle of sum_k E_k' S_k E_k, exactly as the dense loop
                for a in range(nblk):
                    ii, alpha = blk[a]
                    for b in range(nblk):
                        jj, beta = blk[b]
                        if C[ii] > C[jj]:
                            continue
                        dest = lhs.setdefault((C[ii], C[jj]), defaultdict(list))
                        gamma = tuple(x + y for x, y in zip(alpha, beta))
                        dest[gamma].append(Q[a, b])
            continue
        Q = cp.Variable((mk * nB, mk * nB), PSD=True)
        con.grams.append(Q)
        # S_k(x)[ii, jj] = sum_{a,b} Q[a*mk+ii, b*mk+jj] * z_a(x) * z_b(x)
        for ii in range(mk):
            for jj in range(ii, mk):
                key = (C[ii], C[jj])
                dest = lhs.setdefault(key, defaultdict(list))
                for a in range(nB):
                    for b in range(nB):
                        gamma = tuple(x + y for x, y in zip(B[a], B[b]))
                        dest[gamma].append(Q[a * mk + ii, b * mk + jj])

    constraints = []
    entries = set(lhs) | {(i, j) for i, j in nonzero if i <= j}
    for i, j in sorted(entries):
        constraints.extend(
            _match_coefficients(
                lhs.get((i, j), {}), P[i, j].terms, "SOSMatrix entry (%d, %d)" % (i, j)
            )
        )
    return constraints


# ======================================================================
# Problem
# ======================================================================
class Problem:
    """Couples a CVXPY objective with (sparse) SOS constraints.

    Mirrors ``cvxpy.Problem``: ``objective`` is a ``cvxpy.Minimize`` /
    ``cvxpy.Maximize`` over CVXPY decision variables (or ``None`` for a
    feasibility problem), and ``constraints`` may mix :class:`SOS` /
    :class:`SOSMatrix` objects (e.g. created with ``>>``) with ordinary CVXPY
    constraints.
    """

    def __init__(self, objective=None, constraints=()):
        self.objective = objective
        self.constraints = list(constraints)
        self._cvxpy_problem = None
        self.status = None
        self.value = None

    def compile(self):
        """Build (and cache) the underlying ``cvxpy.Problem``."""
        if self._cvxpy_problem is None:
            cons = []
            for c in self.constraints:
                if isinstance(c, (SOS, SOSMatrix)):
                    cons.extend(c.compile())
                else:
                    cons.append(c)
            obj = self.objective if self.objective is not None else cp.Minimize(0)
            self._cvxpy_problem = cp.Problem(obj, cons)
        return self._cvxpy_problem

    def solve(self, solver="SCS", verbose=False, **kwargs):
        prob = self.compile()
        prob.solve(solver=solver, verbose=verbose, **kwargs)
        self.status = prob.status
        self.value = prob.value
        return self.value
