"""Certified GKSL (Lindblad) parameter reconstruction for a single qubit.

Based on Parvaiz, Aspman, Wodecki, Korpas & Marecek, "Identifiability of
Autonomous and Controlled Open Quantum Systems" (arXiv:2501.05270), which
casts open quantum system identification as recovering the Hamiltonian
parameters ``theta`` and the Kossakowski matrix ``gamma`` of the GKSL master
equation from an identified coherence-vector system matrix ``A``, subject to
the physical constraint that ``gamma`` is positive semidefinite (a PMI in
the unknown parameters; the paper suggests polynomial matrix inequality
algorithms for this reconstruction step).

For a qubit (``N = 2``), the coherence vector ``x_j = tr(sigma_j rho)``
evolves as ``xdot = A(theta, gamma) x`` with ``A`` *linear* in the unknowns:
``A = sum_p theta_p A_p + sum_{l<=m} gamma_lm A_lm``, where the coefficient
matrices come from the structure constants of su(2) (eq. (13) of the paper;
we compute them numerically from the master equation below). Given a
measured ``A_meas``, we bound the reconstruction residual

    min || A(theta, gamma) - A_meas ||_F^2   s.t.   gamma >> 0

with :func:`pysparsepmi.pmi_optimize`: the objective is a polynomial in the
9 unknowns (3 Hamiltonian + 6 Kossakowski) and the constraint is a
polynomial matrix inequality. Two scenarios:

* data generated by a *physical* model (``gamma >= 0``): the certified
  lower bound on the residual is 0 — a consistent GKSL model exists;
* data generated by a *non-physical* generator (``gamma`` indefinite): the
  bound is strictly positive — a certificate that **no** GKSL master
  equation with a PSD Kossakowski matrix reproduces the measured dynamics.

Since this instance is convex, cvxpy can solve it directly; the script
cross-checks the SOS bound against the direct solve.
"""
import numpy as np
import cvxpy as cp

import pysparsepmi as psp

# ----------------------------------------------------------------------
# GKSL -> coherence-vector map for one qubit, F_m = sigma_m / sqrt(2)
# ----------------------------------------------------------------------
SX = np.array([[0, 1], [1, 0]], dtype=complex)
SY = np.array([[0, -1j], [1j, 0]], dtype=complex)
SZ = np.array([[1, 0], [0, -1]], dtype=complex)
PAULI = [SX, SY, SZ]
FB = [s / np.sqrt(2) for s in PAULI]  # tr(F_m F_n) = delta_mn


def _hamiltonian_part(p, rho):
    # -i [F_p, rho]
    return -1j * (FB[p] @ rho - rho @ FB[p])


def _dissipator(l, m, rho):
    # F_l rho F_m - (1/2){F_m F_l, rho}
    fmfl = FB[m] @ FB[l]
    return FB[l] @ rho @ FB[m] - 0.5 * (fmfl @ rho + rho @ fmfl)


def _bloch_matrix(gen):
    """3x3 real matrix of x -> tr(sigma_j gen(sigma_k)) / 2."""
    A = np.zeros((3, 3))
    for k in range(3):
        out = gen(PAULI[k])
        for j in range(3):
            A[j, k] = 0.5 * np.real(np.trace(PAULI[j] @ out))
    return A


# coefficient matrices: A = sum_p theta_p A_TH[p] + sum_{l<=m} g_lm A_G[l,m]
A_TH = [_bloch_matrix(lambda r, p=p: _hamiltonian_part(p, r)) for p in range(3)]
A_G = {}
for l in range(3):
    for m in range(l, 3):
        if l == m:
            A_G[(l, m)] = _bloch_matrix(lambda r, l=l: _dissipator(l, l, r))
        else:  # real symmetric gamma: gamma_lm multiplies D_lm + D_ml
            A_G[(l, m)] = _bloch_matrix(
                lambda r, l=l, m=m: _dissipator(l, m, r) + _dissipator(m, l, r)
            )


def bloch_A(theta, gamma):
    A = sum(theta[p] * A_TH[p] for p in range(3))
    for l in range(3):
        for m in range(l, 3):
            A = A + gamma[l, m] * A_G[(l, m)]
    return A


# ----------------------------------------------------------------------
# reconstruction residual as a sparse PMI problem
# ----------------------------------------------------------------------
def certify_residual(A_meas, **solve_opts):
    """Certified lower bound on min ||A(theta, gamma) - A_meas||_F^2, gamma >> 0."""
    v = psp.polyvar(9)
    theta = v[:3]
    gidx = {(0, 0): 3, (0, 1): 4, (0, 2): 5, (1, 1): 6, (1, 2): 7, (2, 2): 8}

    def gamma_lm(l, m):
        return v[gidx[(l, m) if l <= m else (m, l)]]

    zero = psp.Polynomial.zero(9)
    resid = zero
    for j in range(3):
        for k in range(3):
            entry = zero + (-A_meas[j, k])
            for p in range(3):
                entry = entry + theta[p] * A_TH[p][j, k]
            for (l, m), Alm in A_G.items():
                entry = entry + gamma_lm(l, m) * Alm[j, k]
            resid = resid + entry * entry

    K = psp.PolyMatrix(
        [[gamma_lm(l, m) for m in range(3)] for l in range(3)], nvars=9
    )
    return psp.pmi_optimize([[resid]], ineqs=[K], order=1, **solve_opts)


def direct_solve(A_meas):
    """The same problem solved directly (it is convex): reference value."""
    th = cp.Variable(3)
    gam = cp.Variable((3, 3), PSD=True)
    A = sum(th[p] * A_TH[p] for p in range(3))
    for (l, m), Alm in A_G.items():
        A = A + gam[l, m] * Alm
    prob = cp.Problem(cp.Minimize(cp.sum_squares(A - A_meas)))
    prob.solve(solver="SCS", eps=1e-8)
    return prob.value


if __name__ == "__main__":
    opts = dict(solver="SCS", eps=1e-8, max_iters=50000)

    # ground truth: H = 0.4*sqrt(2)*sigma_z (theta = (0, 0, 0.4)), gamma PSD
    theta0 = np.array([0.0, 0.0, 0.4])
    gamma_ok = np.array([[0.30, 0.05, 0.00],
                         [0.05, 0.20, 0.02],
                         [0.00, 0.02, 0.40]])
    assert np.linalg.eigvalsh(gamma_ok).min() > 0

    res = certify_residual(bloch_A(theta0, gamma_ok), **opts)
    print("physical data:      certified residual bound = %10.3e (%s)"
          % (res.value, res.status))
    print("                    -> a consistent GKSL model exists (bound ~ 0)")

    # non-physical generator: indefinite "Kossakowski" matrix
    gamma_bad = gamma_ok - np.diag([0.0, 0.55, 0.0])
    assert np.linalg.eigvalsh(gamma_bad).min() < 0

    A_bad = bloch_A(theta0, gamma_bad)
    res_bad = certify_residual(A_bad, **opts)
    ref = direct_solve(A_bad)
    print("non-physical data:  certified residual bound = %10.3e (%s)"
          % (res_bad.value, res_bad.status))
    print("                    direct convex solve      = %10.3e" % ref)
    print("                    -> no GKSL model with gamma >> 0 fits the data")
